"""Layer 1 jobs — network scrapers and deterministic insight ports.

bootstrap_layer1() registers Layer 1 JobSpecs. Called from registry.py next to
_bootstrap_meta() so app.py stays untouched (check_lib_modules package blindness).
"""

from __future__ import annotations

from typing import Callable

from ..spec import JobSpec
from . import (
    booking_truth,
    competitor_tracker,
    content_ideas_refresh,
    ga4_report,
    golf_news,
    gsc_report,
    insights_hooks,
    insights_reco,
    post_conversion_score,
    reddit_trends,
    seo_rankings,
    site_audit,
    windsor_refresh,
    youtube_trends,
)

LAYER1_JOB_NAMES: tuple[str, ...] = (
    "golf_news",
    "reddit_trends",
    "youtube_trends",
    "seo_rankings",
    "ga4_report",
    "site_audit",
    "competitor_tracker",
    "windsor_refresh",
    "gsc_report",
    "booking_truth",
    "insights_hooks",
    "post_conversion_score",
    "content_ideas_refresh",
    "insights_reco",
)

_ALL_ACTIVE_BRANDS = ("swing-shack", "stick", "bag-drop")
_SS_ONLY = ("swing-shack",)


def layer1_specs() -> list[JobSpec]:
    """Return all Layer 1 JobSpecs."""
    return [
        JobSpec(
            name="golf_news",
            fn=golf_news.run,
            every_seconds=86400,
            timeout_seconds=60,
            best_effort=True,
            criticality="LOW",
            retries=2,
            writes=("golf-news.json",),
            brand_mode="global",
        ),
        JobSpec(
            name="reddit_trends",
            fn=reddit_trends.run,
            every_seconds=86400,
            timeout_seconds=60,
            best_effort=True,
            criticality="LOW",
            retries=2,
            writes=("reddit-trends.json",),
            brand_mode="global",
        ),
        JobSpec(
            name="youtube_trends",
            fn=youtube_trends.run,
            every_seconds=86400,
            timeout_seconds=90,
            best_effort=True,
            criticality="LOW",
            retries=2,
            credentials=("YOUTUBE_API_KEY",),
            writes=("youtube-trends.json",),
            reads=("golf-news.json", "reddit-trends.json"),
            upstream=("golf_news", "reddit_trends"),
            brand_mode="global",
        ),
        JobSpec(
            name="seo_rankings",
            fn=seo_rankings.run,
            every_seconds=86400,
            timeout_seconds=120,
            best_effort=True,
            criticality="MEDIUM",
            retries=1,
            credentials=("UBERSUGGEST_TOKEN_FILE", "SWING_SHACK_DOMAIN"),
            writes=(
                "seo-rankings.json",
                "ubersuggest-domain.json",
                "ubersuggest-competitors.json",
                "ubersuggest-backlinks.json",
            ),
            brand_mode="per_brand",
            brands=_SS_ONLY,
            requires_integrations=("ubersuggest",),
        ),
        JobSpec(
            name="ga4_report",
            fn=ga4_report.run,
            every_seconds=86400,
            timeout_seconds=90,
            best_effort=False,
            criticality="MEDIUM",
            retries=1,
            credentials=("GA4_PROPERTY_ID", "GA4_SERVICE_ACCOUNT_JSON_PATH"),
            writes=("ga4-metrics.json",),
            brand_mode="per_brand",
            brands=_SS_ONLY,
            requires_integrations=("ga4",),
        ),
        JobSpec(
            name="site_audit",
            fn=site_audit.run,
            every_seconds=86400,
            timeout_seconds=90,
            best_effort=True,
            criticality="MEDIUM",
            retries=2,
            writes=("seo-audit.json", "geo-audit.json"),
            brand_mode="per_brand",
            brands=_SS_ONLY,
            requires_integrations=("ubersuggest",),
        ),
        JobSpec(
            name="competitor_tracker",
            fn=competitor_tracker.run,
            every_seconds=604800,
            timeout_seconds=120,
            best_effort=True,
            criticality="MEDIUM",
            retries=1,
            credentials=("META_SYSTEM_USER_TOKEN",),
            writes=("competitor-tracker.json",),
            reads=("competitor-tracker.json",),
            brand_mode="per_brand",
            requires_integrations=("meta",),
        ),
        JobSpec(
            name="windsor_refresh",
            fn=windsor_refresh.run,
            every_seconds=86400,
            timeout_seconds=90,
            best_effort=True,
            criticality="MEDIUM",
            retries=1,
            credentials=("WINDSOR_API_KEY",),
            writes=("meta-ads.json", "google-ads.json"),
            reads=("ga4-metrics.json",),
            upstream=("ga4_report",),
            brand_mode="per_brand",
            brands=_SS_ONLY,
            requires_integrations=("windsor",),
        ),
        JobSpec(
            name="gsc_report",
            fn=gsc_report.run,
            every_seconds=86400,
            timeout_seconds=90,
            best_effort=True,
            criticality="MEDIUM",
            retries=1,
            credentials=("GA4_PROPERTY_ID", "GA4_SERVICE_ACCOUNT_JSON_PATH"),
            writes=("search-console.json",),
            upstream=("ga4_report",),
            brand_mode="per_brand",
            brands=_SS_ONLY,
            requires_integrations=("gsc",),
        ),
        JobSpec(
            name="booking_truth",
            fn=booking_truth.run,
            every_seconds=86400,
            timeout_seconds=90,
            best_effort=True,
            criticality="MEDIUM",
            retries=1,
            credentials=("GA4_PROPERTY_ID", "GA4_SERVICE_ACCOUNT_JSON_PATH"),
            writes=("booking-events.json", "leads.json", "lead-quality.json"),
            reads=("reddit-trends.json", "booking-events.json"),
            upstream=("ga4_report", "reddit_trends"),
            brand_mode="per_brand",
            brands=_SS_ONLY,
            requires_integrations=("ga4",),
            shared_reads=("reddit-trends.json",),
        ),
        JobSpec(
            name="insights_hooks",
            fn=insights_hooks.run,
            every_seconds=86400,
            timeout_seconds=120,
            best_effort=False,
            criticality="HIGH",
            retries=0,
            writes=("hook-bank.json", "youtube-hook-signals.json"),
            reads=(
                "ig-analytics.json",
                "youtube-trends.json",
                "youtube-hook-signals.json",
                "golf-news.json",
                "reddit-trends.json",
                "hook-bank.json",
            ),
            upstream=("meta_refresh", "youtube_trends"),
            brand_mode="per_brand",
            requires_integrations=("meta",),
            shared_reads=(
                "youtube-trends.json",
                "golf-news.json",
                "reddit-trends.json",
            ),
        ),
        JobSpec(
            name="post_conversion_score",
            fn=post_conversion_score.run,
            every_seconds=86400,
            timeout_seconds=120,
            best_effort=True,
            criticality="HIGH",
            retries=0,
            credentials=("GA4_PROPERTY_ID", "GA4_SERVICE_ACCOUNT_JSON_PATH"),
            writes=("post-conversion-score.json",),
            reads=("ig-business-analytics.json", "ga4-metrics.json"),
            upstream=("meta_refresh", "ga4_report"),
            brand_mode="per_brand",
            requires_integrations=("meta",),
        ),
        JobSpec(
            name="content_ideas_refresh",
            fn=content_ideas_refresh.run,
            every_seconds=86400,
            timeout_seconds=60,
            best_effort=True,
            criticality="LOW",
            retries=1,
            writes=("content-ideas.json",),
            reads=(
                "missed-opportunities.json",
                "reddit-trends.json",
                "hook-bank.json",
                "competitor-tracker.json",
                "content-ideas.json",
            ),
            upstream=("insights_hooks", "insights_reco", "competitor_tracker"),
            brand_mode="per_brand",
            brands=_ALL_ACTIVE_BRANDS,
            shared_reads=("reddit-trends.json",),
        ),
        JobSpec(
            name="insights_reco",
            fn=insights_reco.run,
            every_seconds=86400,
            timeout_seconds=180,
            best_effort=False,
            criticality="MEDIUM",
            retries=0,
            writes=(
                "anomaly-alerts.json",
                "missed-opportunities.json",
                "funnel-leaks.json",
                "conversion-attribution.json",
                "retargeting-recommendations.json",
                "recommendation-scores.json",
                "recommendation-outcomes.json",
                "website-insights.json",
            ),
            reads=(
                "ga4-metrics.json",
                "seo-rankings.json",
                "ig-analytics.json",
                "hook-bank.json",
                "geo-audit.json",
                "recommendation-scores.json",
                "meta-ads.json",
                "google-ads.json",
                "search-console.json",
                "booking-events.json",
            ),
            upstream=(
                "insights_hooks",
                "ga4_report",
                "seo_rankings",
                "site_audit",
                "windsor_refresh",
                "gsc_report",
                "booking_truth",
            ),
            brand_mode="per_brand",
            brands=("swing-shack", "stick"),
        ),
    ]


def bootstrap_layer1(register: Callable[[JobSpec], None] | None = None) -> None:
    """Register all Layer 1 JobSpecs. Pass register to avoid circular imports."""
    if register is None:
        from ..registry import register as register  # noqa: PLC0415

    for spec in layer1_specs():
        register(spec)
